### 박정빈 회원 가입 

POST http://localhost:5000/sign-up HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "name" : "박정빈",
    "email" : "ggamsi0418@naver.com",
    "password" :"test1234",
    "profile" : "구공팩토리 3기 백엔드 개발 공부 중"
}


### 홍길동 회원 가입 

POST http://localhost:5000/sign-up HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "name" : "홍길동",
    "email" : "gildong@naver.com",
    "password" :"test5678",
    "profile" : "동해 번쩍, 서해 번쩍"
}

### 박정빈 트윗 글 작성

POST http://localhost:5000/tweet HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "id" : "1",
    "tweet" : "My First Tweet"
}

### 홍길동 트윗 글 작성

POST http://localhost:5000/tweet HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "id" : "2",
    "tweet" : "Hello, world!"
}


### 팔로우 하기

POST http://localhost:5000/follow HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "follow" : 2,
    "id" : 1
}


### 언팔로우 하기

POST http://localhost:5000/unfollow HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "unfollow" : 2,
    "id" : 1
}


### 타임라인 확인하기
GET http://localhost:5000/timeline/1 HTTP/1.1
Content-Type: application/json;charset=UTF-8



////////////////// DB 연결 이후 ////////////////////////
### DB에 연결된 sign-up 엔드포인트 테스트
POST http://localhost:5000/sign-up HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "name"  :   "코난",
    "email" :   "conan@gmail.com",
    "password"  :   "test6642",
    "profile"   :   "Software Engineer"
}


### DB에 연결된 tweet 엔드포인트 테스트
POST http://localhost:5000/tweet HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "id": "5",
    "tweet": "안녕하세요. 만나서 반갑습니다."
}


### DB에 연결된 follow 엔드포인트 테스트
POST http://localhost:5000/follow HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "follow" : 9,
    "id" : 5
}


### DB에 연결된 unfollow 엔드포인트 테스트
POST http://localhost:5000/unfollow HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "unfollow" : 7,
    "id" : 5
}



### DB에 연결된 timeline 엔드포인트 테스트
GET http://localhost:5000/timeline/5 HTTP/1.1
Content-Type: application/json;charset=UTF-8
